name: tree_sitter_dart
description: Tree-sitter grammar for Dart language using Dart Native FFI bindings
version: 0.1.2
repository: https://github.com/UserNobody14/tree-sitter-dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  ffi: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.0
