name: "TreeSitter"
description: "C Bindings to the TreeSitter library"
output: 'lib/src/generated_bindings.dart'
headers:
  entry-points:
    - 'tree-sitter/lib/include/tree_sitter/api.h'
  include-directives:
    - 'tree-sitter/lib/include/tree_sitter/api.h'
functions:
  symbol-address:
    include:
      - 'ts_parser_delete'
      - 'ts_tree_delete'
      - 'ts_tree_cursor_delete'
      - 'ts_query_delete'
      - 'ts_query_cursor_delete'
silence-enum-warning: true
# Configure ffigen to generate @Native annotations (Dart 3.0+)
# This enables efficient static linking instead of dynamic library loading
# Note: assetId is omitted to allow fallback to process lookup
ffi-native:
llvm-path:
  - '/usr/lib/llvm-18'
  - '/usr/lib/llvm-17'
  - '/usr/lib/llvm-16'
  - '/usr/lib/llvm-14'
  - '/usr/lib/llvm-11'
  - '/usr/local/opt/llvm'