name: "TSParser"
description: "C Bindings to the TreeSitter Parser library"
output: 'lib/src/parser_generated_bindings.dart'
headers:
  entry-points:
    - 'tree-sitter/lib/include/tree_sitter/parser.h'
  include-directives:
    - 'tree-sitter/lib/include/tree_sitter/parser.h'