name: "TSParser"
description: "C Bindings to the TreeSitter Parser library"
output: 'lib/src/parser_generated_bindings.dart'
headers:
  entry-points:
    - 'tree-sitter/lib/include/tree_sitter/parser.h'
  include-directives:
    - 'tree-sitter/lib/include/tree_sitter/parser.h'
# Configure ffigen to generate @Native annotations (Dart 3.0+)
# This enables efficient static linking instead of dynamic library loading
ffi-native:
  enabled: true
  asset-id: 'package:tree_sitter/libtree-sitter.so'
llvm-path:
  - '/usr/lib/llvm-14'
  - '/usr/lib/llvm-11'
  - '/usr/local/opt/llvm'