name: tree_sitter
description: A tree sitter parsing library
version: 0.2.0
repository: https://github.com/UserNobody14/tree-sitter-dart

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  dylib: ^0.3.3
  args: ^2.7.0
  ffi: ^2.1.4
  freezed_annotation: ^3.1.0
  path: ^1.9.1
  json_annotation: ^4.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
  ffigen: ^19.1.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  build_runner: ^2.9.0

executables:
  tsdart: gen_grammar  